baseURL: /
languageCode: en-us
title: CIT计算机兴趣小组
theme: "PaperMod"


menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: friend
      name: friends
      url: /friends
      weight: 30

params:
    homeInfoParams:
        Title: "Welcome"
        Content: >
            欢迎加入CIT兴趣学习小组，**CIT** 是一个非赢利性组织，由一群爱好计算机的工程师发起，从这出发，成为顶级工程师。
             - Join us become better
             - Do give a 🌟 on Github !
             - This is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).



