baseURL: /
languageCode: en-us
title: CIT计算机兴趣小组
theme: "PaperMod"


menu:
  main:
    - identifier: maintainers
      name: 讲师
      url: /maintainers
      weight: 100
    - identifier: courses
      name: 课程
      url: /courses
      weight: 10
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 40
    # - identifier: tags
    #   name: 标签
    #   url: /tags/
    #   weight: 40
    - identifier: timeline
      name: 历程
      url: /posts/timeline/
      weight: 40      

params:
  homeInfoParams:
      Title: "Welcome"
      Content: >
          欢迎加入CIT兴趣学习小组，**CIT** 是一个非赢利性组织，由一群爱好计算机的工程师发起，从这出发，成为顶级工程师。
            - Join us become better
            - Do give a 🌟 on Github !
            - This is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
  comments: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
      

taxonomies:
  category: categories
  tag: tags